# Generated by Django 5.0.6 on 2025-10-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCache',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipos', models.JSONField(default=list)),
                ('imagemUrl', models.URLField(max_length=400)),
                ('dtAtualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache de Pokémon',
                'verbose_name_plural': 'Cache de Pokémon',
            },
        ),
    ]
